export const FORM_ACTION_TYPES = {
    CHANGE_INPUT: "CHANGE_INPUT",
    ADD_TAG: "ADD_TAG",
    REMOVE_TAG: "REMOVE_TAG",
    INCREASE_QTY: "INCREASE_QTY",
    DECREASE_QTY: "DECREASE_QTY",
    RESET_FORM: "RESET_FORM",
}